services:
  postgres:
    image: postgres:15
    container_name: szept-db
    restart: always
    environment:
      POSTGRES_USER: szeptuser
      POSTGRES_PASSWORD: szeptpass
      POSTGRES_DB: szeptdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: szept-backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./apps/backend/.env
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: szept-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./apps/frontend/.env
    ports:
      - "3000:3000"

volumes:
  pgdata:
