FROM node:20-alpine
WORKDIR /app
RUN npm i -g pnpm
COPY package.json pnpm-workspace.yaml ./
COPY apps/frontend/package.json ./apps/frontend/
COPY packages ./packages
RUN pnpm install --filter frontend...
WORKDIR /app/apps/frontend
EXPOSE 3000
CMD ["pnpm", "dev"]
